Repository dora-farm/farm-dora-client, pull requests merged in 2025-05, with the labels that each got.

#54 [FDORA-112] feat : 판매자 승인, 사용자 관리
  src/App.jsx
  src/common/utils/fromToken.js
  src/features/auth/components/JoinSellerForm.jsx
  src/features/auth/components/Joinform.jsx
  src/features/auth/components/LoginForm.jsx
  src/features/auth/hooks/useAddressForm.js
  src/features/auth/hooks/useFormValidation.js
  src/features/auth/services/addressService.js
  src/features/auth/services/authService.js
  src/features/auth/services/findService.js
  src/features/auth/services/userUpdateService.js
  src/features/auth/services/validationService.js
  src/layouts/AdminSidebar.jsx
  src/layouts/Header.jsx
  src/pages/adminpage/AdminUser.jsx
  src/pages/adminpage/SellerApproval.jsx
  src/pages/adminpage/components/UserListSection.jsx
  src/pages/adminpage/components/UserSearchSection.jsx
  src/pages/adminpage/components/user/UserCheckSort.jsx
  src/pages/adminpage/components/user/UserKeyword.jsx
  src/pages/adminpage/components/user/UserSelectSort.jsx
  src/pages/adminpage/components/user/UserTable.jsx
  src/pages/adminpage/modal/SellerShowFileModal.jsx
  src/pages/event/EventDetail.jsx
  src/pages/user/DeleteAccount.jsx
  src/pages/user/EditProfile.jsx
  src/pages/user/ManageAddress.jsx
  src/pages/user/modal/ManageAddressModal.jsx
Labels: feat

#55 [FDORA-75] feat: 실시간 상품 랭킹 조회 화면 구현
  src/common/components/ProductCard.jsx
  src/pages/Home.jsx
  src/pages/category/Category.jsx
  src/pages/product/ProductQnA.jsx
  src/pages/product/ProductSummary.jsx
  src/pages/product/RelatedProducts.jsx
Labels: feat

#73 [FDORA-81] feat: 배너 사진 슬라이더 구현
  src/pages/BannerSlider.jsx
  src/pages/Home.jsx
Labels: feat

#74 [FDORA-153] feat: 주문 화면 구현
  src/App.jsx
  src/common/contexts/BasketContext.jsx
  src/layouts/Header.jsx
  src/pages/category/Category.jsx
  src/pages/order/OrderCompletePage.jsx
  src/pages/order/OrderPage.jsx
  src/pages/product/ProductSummary.jsx
  src/pages/product/RelatedProducts.jsx
  src/pages/user/Basket.jsx
  src/pages/user/BasketItem.jsx
  src/pages/user/hooks/useBasket.jsx
Labels: feat

#78 [FDORA-167] refactor : 최종수정
  src/common/components/modal/AlertModal2.jsx
  src/common/components/search/BasicBtn.jsx
  src/features/auth/components/EditProFileFrom.jsx
  src/features/auth/components/JoinSellerForm.jsx
  src/features/auth/components/Joinform.jsx
  src/features/auth/components/LoginForm.jsx
  src/features/auth/components/SocialLoginForm.jsx
  src/features/auth/hooks/useAddressForm.js
  src/features/auth/hooks/useFormValidation.js
  src/features/auth/services/addressService.js
  src/features/auth/services/authService.js
  src/features/auth/services/userUpdateService.js
  src/features/auth/services/validationService.js
  src/layouts/Header.jsx
  src/pages/Home.jsx
  src/pages/adminpage/AdminUser.jsx
  src/pages/adminpage/SellerApproval.jsx
  src/pages/auth/Login.jsx
  src/pages/seller/ordermanage/components/SearchForm.jsx
  src/pages/user/DeleteAccount.jsx
  src/pages/user/EditProfile.jsx
  src/pages/user/ManageAddress.jsx
  src/pages/user/modal/ManageAddressModal.jsx
Labels: bug, refactor

#80 [FDORA-170] refactor : 카카오 로고 제거
  src/assets/images/KakaoI.png
  src/features/auth/components/SocialLoginForm.jsx
Labels: refactor

#82 [FDORA-173] refactor : url 수정
  src/features/auth/components/JoinSellerForm.jsx
  src/features/auth/components/Joinform.jsx
  src/features/auth/services/addressService.js
  src/features/auth/services/authService.js
  src/features/auth/services/findService.js
  src/features/auth/services/userUpdateService.js
  src/features/auth/services/validationService.js
  src/pages/adminpage/AdminUser.jsx
  src/pages/adminpage/SellerApproval.jsx
  src/pages/order/OrderPage.jsx
Labels: refactor

#83 [FDORA-175] fix: 리뷰/반품 이미지 조회 화면 수정
  src/pages/seller/ordermanage/Exchange.jsx
  src/pages/user/components/RefundItem.jsx
  src/pages/user/modal/PaymentInfo.jsx
  src/pages/user/modal/ReviewModal.jsx
Labels: bug
